import "../styles/globals.css";
import type { AppProps } from "next/app";
import styled, { ThemeProvider } from "styled-components";
import Head from "next/head";
import { wrapper } from "../redux";

const BodySection = styled.body`
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	width: 100vw;
	height: 100vh;
`;

function MyApp({ Component, pageProps }: AppProps) {
	return (
		<BodySection>
			<Head>
				<title>Lost Gold |</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Component {...pageProps} />
		</BodySection>
	);
}

export default wrapper.withRedux(MyApp);
