import Head from "next/head";
import { DefaultSeo } from "next-seo";
import { RecoilRoot } from "recoil";
import { QueryClient, QueryClientProvider } from "react-query";
// import { ReactQueryDevTools } from 'react-query/devtools';

import styled from "styled-components";
import "../styles/globals.css";
import { color } from "../styles/theme";

import Header from "./Header";
import Footer from "./Footer";
import Loading from "../components/atoms/Loading";

function MyApp({ Component, pageProps }: any) {
	const queryClient = new QueryClient({
		defaultOptions: {
			queries: {
				refetchOnWindowFocus: false,
			},
		},
	});

	return (
		<QueryClientProvider client={queryClient}>
			<AppSection>
				<Head>
					<title>Lost Gold |</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<DefaultSeo
					title="Lost Gold"
					description="당신의 한달 골드량을 한눈에 확인시켜드립니다"
					canonical="https://lostgold.vercel.app/"
					openGraph={{
						type: "website",
						url: "https://lostgold.vercel.app/",
						title: "간편한 골드 계산기, Lost Gold",
						description: "당신의 한달 골드량을 한눈에 확인시켜드립니다",
						images: [{ url: "https://lostgold.vercel.app/images/seo_bg.png" }],
						site_name: "Lost Gold",
					}}
				/>

				<RecoilRoot>
					<Loading />

					<Header />
					<Component {...pageProps} />
					<Footer />
				</RecoilRoot>

				<script
					async
					src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6443631393154145"
					crossOrigin="anonymous"
				></script>
			</AppSection>
		</QueryClientProvider>
	);
}

const AppSection = styled.section`
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: center;
	width: 100vw;
	height: 100vh;
	overflow: hidden;
	background: ${color.darkGray};
`;

export default MyApp;
