import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import styled from "styled-components";
import { pageDefault } from "../styles/theme";
import Header from "../components/Header";

const Index: NextPage = () => {
	const HomeSection = styled.header`
		${pageDefault}
	`;

	return (
		<div className={styles.container}>
			<Head>
				<title>Lost Gold |</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HomeSection>test Home page</HomeSection>
		</div>
	);
};

export default Index;
