import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/dist/client/router";
import { useEffect } from "react";
import Header from "../components/Header";
import MyApp from "./_app";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Lost Gold |</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* 헤더 */}
			<Header />

			{/* 메뉴 */}

			{/* 컨텐츠 */}
			{/* <MyApp
				pageProps={undefined}
				Component={undefined}
				router={undefined}
			></MyApp> */}
		</div>
	);
};

export default Home;
